In [44]:
import pandas as pd

In [45]:
df=pd.read_csv('data_frame.csv')
df

,BILL DATE,CUSTOMER,mat,QUANTITY,region,MATERIAL description
0,05-02-2020,A ONE ISPAT PVT LTD,SILICO MANGANESE Mn 60% - 65%,25.0,Andhra Pradesh,SILICO MANGANESE Mn 60% - 65%
1,25-01-2020,A ONE ISPAT PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Andhra Pradesh,SILICO MANGANESE Mn 60% - 65%
2,04-03-2020,A ONE STEEL AND ALLOYS PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Karnataka,SILICO MANGANESE Mn 60% - 65%
3,24-01-2020,A ONE STEEL AND ALLOYS PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Karnataka,SILICO MANGANESE Mn 60% - 65%
4,21-01-2020,A ONE STEEL AND ALLOYS PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Karnataka,SILICO MANGANESE Mn 60% - 65%
...,...,...,...,...,...,...
9533,21-04-2022,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,25.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9534,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,24.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9535,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,24.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9536,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,24.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9537,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,23.0,Thailand,SILICO MANGANESE Mn 65% to 70%

In [46]:
df['region']=df['region'].str.strip()

In [47]:
df['CUSTOMER']=df['CUSTOMER'].str.strip()

In [48]:
df['MATERIAL description']=df['MATERIAL description'].str.strip()

In [49]:
df['MATERIAL description'].unique()

array(['SILICO MANGANESE Mn 60% - 65%', 'SILICO MANGANESE DOMESTIC',
       'SILICO MANGANESE Mn 65% to 70%', 'SILICO MANGANESE EXPORT',
       'SILICO MANGANESE Mn 65% to 70% LOW PHOS',
       'SILICO MANGANESE Mn 60% to 65% LOW PHOS',
       'SILICO MANGANESE Mn BELOW 60%', 'FERRO MANGANESE 75% - 80%',
       'FERRO MANGANESE Mn 70% - 75%'], dtype=object)

In [50]:
df['CUSTOMER'].unique()

array(['A ONE ISPAT PVT LTD', 'A ONE STEEL AND ALLOYS PVT LTD',
       'A ONE STEELS INDIA (PVT) LTD',
       'AGARWAL INDUCTION FURNACE PVT LTD', 'AGRA CASTINGS PVT LTD',
       'ARABIAN GULF STEEL INDUSTRIES LLC', 'ASIA MINERALS LIMITED',
       'AVEKS (SUISSE) S A', 'BAHUBALI OVERSEAS',
       'CONCORDIA RESOURCES LIMITED', 'D S ALLOYD PVT LTD',
       'DAHUTI INTERNATIONAL LIMITED', 'EKAGRATA ENTERPRISES PTE LTD',
       'EL MARAKBY STEEL', 'EMIRATES STEEL INDUSTRIES PJSC',
       'EXCELCO CORPORATION', 'FELMAN TRADING EUROPE AG',
       'GBF BONTEX TAIWAN INC', 'GRETA METAL PTE LTD', 'HANWA CO LTD',
       'HOJIN IND CO LTD', 'IMETALS GROUP TRADING DWC LLC',
       'INDUSTRIAL METALLURGICAL SOLUTIONS', 'INNOVATION WORLDWIDE DMCC',
       'INTERNATIONAL METALLURGICAL GROUP',
       'JAI HIND WIRE ROD MILLS PVT LTD',
       'KAMACHI INDUSTRIES LIMITED(SMD DIV)', 'KANIKA ISPAT PRIVATE LTD',
       'KAY BEE INDUSTRIAL ALLOYS (P) LTD',
       'KAYBEE INDUSTRIAL ALLOYS (P) LTD', 'KEVIN STEELS PVT LTD',
       'L & Y ASIA PACIFIC LTD', 'LEO OVERSEAS',
       'MAA MAHAMAYA INDUSTRIES LTD', 'MAALU FERRO ALLOYS PVT LTD',
       'MAHRISHI ALLOYS PVT LTD', 'MANAGER (STORES) RECEIPTS, PS-II',
       'MEENAKSHI STEELS', 'MEENAKSHI UDYOG (INDIA) PVT LTD',
       'METAL IMPEX', 'MIL STEEL AND POWER LIMITED',
       'MILLION LINK (CHINA) INVESTMENT LTD', 'MITSUI & CO LTD',
       'MORTEX INDIA', 'MRIDUL STEEL COMPANY',
       'NAGPUR MINERALS AND CHEMICALS', 'NORECOM LIMITED',
       'OSWAL MINERALS LIMITED', 'PREMIER INDUSTRIAL CORPORATION LTD',
       'PULKIT METALS PVT LTD', 'PUSHPIT STEELS PRIVATE LIMITED',
       'RAJ TRADERS', 'RAMA HI-POWER TECH', 'SARITA METAL & ALLOYS',
       'SENTUO STEEL LIMITED', 'SHREEYAM POWER & STEEL INDUSTRIES L',
       'SHRI TIRUPATI STEEL CAST LIMITED', 'SIDENAL',
       'SR MANAGER FINANCE - RAW MATERIAL',
       'SREE RENGARAAJ STEEL AND ALLOYS PVT',
       'SREE RENGARAJ ISPAT INDUSTRIES PVT', 'SRG MINERALS & METALS',
       'STAIN LESS METALS GENERAL TRADING F', 'STEELFORCE NV',
       'SUN TALENT INDUSTRIAL CO LTD', 'SURYADEV ALLOYS & POWER PVT LTD',
       'TA CORPORATION PVT LTD', 'TARSUN STEELS INDIA PRIVATE LIMITED',
       'TUF METALLURGICAL PVT LTD', 'UJJWAL TRADE LINK',
       'UNIVERSAL HI-TECH EQUIPMENTS FZE', 'VGK STEELS',
       'VINAYAK STEELS LIMITED', 'VRKP SPONGE AND POWER PLANT LLP',
       'BARBIL MINING AND INDUSTRIES PVT LI', 'ICON FERRO ALLOYS',
       'KAIZEN COLD FORMED STEEL PVT LTD', 'KAY BEE ALLOYS AND METALS',
       'KHAYATI STEEL INDUSTRIES PVT LTD', 'LOTUS STEELS',
       'METALLIC FERRO ALLOYS LLP', 'PLATINUM STEELS',
       'RDTMT STEELS INDIA PVT LTD', 'S.R.S STEEL PRIVATE LIMITED',
       'SRS ISPATT PRIVATE LIMITED - SALEM', 'SSCA FUELS PRIVATE LIMITED',
       'SUGNA METALS LIMITED', 'UDDISH ISPAT', 'VEDIKA METALS PVT LTD',
       'AGNI STEELS PRIVATE LIMITED', 'ANJANEY FERRO ALLOYS LTD',
       'B B MINERALS AND METALS', 'GOYAL ENERGY AND STEEL PVT LTD',
       'JAYA SAKTHI CASTING INDIA PVT LTD', 'KUSHAL CHEMICALS',
       'NAGPUR MINERALS & CHEMICALS', 'SARDA ENERGY & MINERALS LTD.',
       'AB METALS PTE. LTD', 'ACARER METAL SANAYI VE TICARET A.S',
       'ARCELORMITTAL BRASIL S/A', 'CHARISMA RESOURCES LIMITED',
       'DIVIJ ASSOCIATE PTE LTD', 'DUFERCO ASIA PTE LTD', 'DUFERCO SA',
       'EREGLI DEMIR VE CELIK FABRIKALARI T', 'GALMET S.P.A.',
       'GLENCORE INTERNATIONAL AG', 'GLOBAL PRATEK PTE LTD',
       'GME METALS SRL', 'GMI COMMODITIES AB',
       'ICDAS CELIK ENERJI TERSANE VE ULASI', 'INTERTRADE KOMPANI',
       'ISKENDERUN DEMIR VE CELIK A S', 'JFE SOHJI CORPORATION',
       'LAMED INVESTMENT AND TRADE CO LTD', 'METALLEGHE SPA', 'MTALX',
       'NIPPON STEEL TRADING CORPORATION', 'RONLY LIMITED',
       'SANTAS FAR EAST COMPANY', 'SIAM YAMATO STEEL CO LTD',
       'STEELCO FOR STEEL TRADING', 'STEMCOR (S.E.A) PTE LTD',
       'SULB COMPANY B S C CLOSED', 'TYVIN INTERNATION CO LTD',
       'UNI METAL CO LTD', 'UNITED STEEL INDUSTRIAL COMPANY(K S',
       'VIMET AG', 'WORLD METALS & ALLOYS FZC', 'A.T.E. MASKATI LTD',
       'ARCELORMITTAL COMERCIO EXTERIOR S/A', 'ELMET SA de CV',
       'FORSTEEL SRL', 'ISKENDERUN IRON & STEEL CO.',
       'JINDAL SHADEED IRON & STEEL CO LLC', 'LEMETCO GMBH',
       'MOHAMED ALI ABD EL GHANY', 'VAMANCORE PTE LTD', 'UMC METALS LTD'],
      dtype=object)

In [51]:
df['MATERIAL description'].unique()

array(['SILICO MANGANESE Mn 60% - 65%', 'SILICO MANGANESE DOMESTIC',
       'SILICO MANGANESE Mn 65% to 70%', 'SILICO MANGANESE EXPORT',
       'SILICO MANGANESE Mn 65% to 70% LOW PHOS',
       'SILICO MANGANESE Mn 60% to 65% LOW PHOS',
       'SILICO MANGANESE Mn BELOW 60%', 'FERRO MANGANESE 75% - 80%',
       'FERRO MANGANESE Mn 70% - 75%'], dtype=object)

In [52]:
df = df.drop(df[df['QUANTITY'] < 0].index)
df

,BILL DATE,CUSTOMER,mat,QUANTITY,region,MATERIAL description
0,05-02-2020,A ONE ISPAT PVT LTD,SILICO MANGANESE Mn 60% - 65%,25.0,Andhra Pradesh,SILICO MANGANESE Mn 60% - 65%
1,25-01-2020,A ONE ISPAT PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Andhra Pradesh,SILICO MANGANESE Mn 60% - 65%
2,04-03-2020,A ONE STEEL AND ALLOYS PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Karnataka,SILICO MANGANESE Mn 60% - 65%
3,24-01-2020,A ONE STEEL AND ALLOYS PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Karnataka,SILICO MANGANESE Mn 60% - 65%
4,21-01-2020,A ONE STEEL AND ALLOYS PVT LTD,SILICO MANGANESE Mn 60% - 65%,30.0,Karnataka,SILICO MANGANESE Mn 60% - 65%
...,...,...,...,...,...,...
9533,21-04-2022,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,25.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9534,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,24.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9535,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,24.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9536,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,24.0,Thailand,SILICO MANGANESE Mn 65% to 70%
9537,09-10-2021,UMC METALS LTD,SILICO MANGANESE Mn 65% to 70%,23.0,Thailand,SILICO MANGANESE Mn 65% to 70%

In [53]:
df['day']=df['BILL DATE'].str.split('-').str[0]
df['month']=df['BILL DATE'].str.split('-').str[1]
df['day']=df['day'].astype(int)
df['month']=df['month'].astype(int)

In [54]:
df=df.drop('mat',axis=1)

In [55]:
df["cus-mat"] =df["MATERIAL description"]
df=df.drop(['BILL DATE','CUSTOMER','MATERIAL description'],axis=1)
#df.drop('mat',axis=1)
df

      QUANTITY          region  day  month                         cus-mat
0         25.0  Andhra Pradesh    5      2   SILICO MANGANESE Mn 60% - 65%
1         30.0  Andhra Pradesh   25      1   SILICO MANGANESE Mn 60% - 65%
2         30.0       Karnataka    4      3   SILICO MANGANESE Mn 60% - 65%
3         30.0       Karnataka   24      1   SILICO MANGANESE Mn 60% - 65%
4         30.0       Karnataka   21      1   SILICO MANGANESE Mn 60% - 65%
...        ...             ...  ...    ...                             ...
9533      25.0        Thailand   21      4  SILICO MANGANESE Mn 65% to 70%
9534      24.0        Thailand    9     10  SILICO MANGANESE Mn 65% to 70%
9535      24.0        Thailand    9     10  SILICO MANGANESE Mn 65% to 70%
9536      24.0        Thailand    9     10  SILICO MANGANESE Mn 65% to 70%
9537      23.0        Thailand    9     10  SILICO MANGANESE Mn 65% to 70%

[9396 rows x 5 columns]

In [56]:
df["cus-mat"].unique()

array(['SILICO MANGANESE Mn 60% - 65%', 'SILICO MANGANESE DOMESTIC',
       'SILICO MANGANESE Mn 65% to 70%', 'SILICO MANGANESE EXPORT',
       'SILICO MANGANESE Mn 65% to 70% LOW PHOS',
       'SILICO MANGANESE Mn 60% to 65% LOW PHOS',
       'SILICO MANGANESE Mn BELOW 60%', 'FERRO MANGANESE 75% - 80%',
       'FERRO MANGANESE Mn 70% - 75%'], dtype=object)

In [57]:
import pandas as pd
import re

# Sample DataFrame with a column containing uneven spaces
data = {'cus-mat1': ['SILICO MANGANESE Mn 60% - 65%', 'SILICO MANGANESE DOMESTIC',
       'SILICO MANGANESE Mn 65% to 70%', 'SILICO MANGANESE EXPORT',
       'SILICO MANGANESE Mn 65% to 70% LOW PHOS',
       'SILICO MANGANESE Mn 60% to 65% LOW PHOS',
       'SILICO MANGANESE Mn BELOW 60%', 'FERRO MANGANESE 75% - 80%',
       'FERRO MANGANESE Mn 70% - 75%']}
df_space = pd.DataFrame(data)
df_space

                                  cus-mat1
0            SILICO MANGANESE Mn 60% - 65%
1                SILICO MANGANESE DOMESTIC
2           SILICO MANGANESE Mn 65% to 70%
3                  SILICO MANGANESE EXPORT
4  SILICO MANGANESE Mn 65% to 70% LOW PHOS
5  SILICO MANGANESE Mn 60% to 65% LOW PHOS
6            SILICO MANGANESE Mn BELOW 60%
7                FERRO MANGANESE 75% - 80%
8             FERRO MANGANESE Mn 70% - 75%

In [58]:
def remove_extra_spaces(text):
    
    return re.sub(r'\s+', ' ', text).strip()

#  # Apply the function to the column with uneven spaces
df_space['cus-mat1'] = df_space['cus-mat1'].apply(remove_extra_spaces)
df_space

                                  cus-mat1
0            SILICO MANGANESE Mn 60% - 65%
1                SILICO MANGANESE DOMESTIC
2           SILICO MANGANESE Mn 65% to 70%
3                  SILICO MANGANESE EXPORT
4  SILICO MANGANESE Mn 65% to 70% LOW PHOS
5  SILICO MANGANESE Mn 60% to 65% LOW PHOS
6            SILICO MANGANESE Mn BELOW 60%
7                FERRO MANGANESE 75% - 80%
8             FERRO MANGANESE Mn 70% - 75%

In [59]:
from sklearn.preprocessing import LabelEncoder

# Perform label encoding
label_encoder1 = LabelEncoder()
label_encoder1.fit(df['cus-mat'])

LabelEncoder()

In [60]:
import pickle
filename = 'cus-mat.pkl'
pickle.dump(label_encoder1, open(filename, 'wb'))

In [61]:
df['cus-mat'] = label_encoder1.transform(df['cus-mat'])

In [62]:
labels = label_encoder1.classes_
labels
#A ONE ISPAT PVT LTD-SILICO MANGANESE Mn 60% - 65%

array(['FERRO MANGANESE 75% - 80%', 'FERRO MANGANESE Mn 70% - 75%',
       'SILICO MANGANESE DOMESTIC', 'SILICO MANGANESE EXPORT',
       'SILICO MANGANESE Mn 60% - 65%',
       'SILICO MANGANESE Mn 60% to 65% LOW PHOS',
       'SILICO MANGANESE Mn 65% to 70%',
       'SILICO MANGANESE Mn 65% to 70% LOW PHOS',
       'SILICO MANGANESE Mn BELOW 60%'], dtype=object)

In [63]:
#'WORLD METALS & ALLOYS FZC-SILICO MANGANESE Mn 65% to 70% LOW PHOS'

In [64]:
df

      QUANTITY          region  day  month  cus-mat
0         25.0  Andhra Pradesh    5      2        4
1         30.0  Andhra Pradesh   25      1        4
2         30.0       Karnataka    4      3        4
3         30.0       Karnataka   24      1        4
4         30.0       Karnataka   21      1        4
...        ...             ...  ...    ...      ...
9533      25.0        Thailand   21      4        6
9534      24.0        Thailand    9     10        6
9535      24.0        Thailand    9     10        6
9536      24.0        Thailand    9     10        6
9537      23.0        Thailand    9     10        6

[9396 rows x 5 columns]

In [65]:


# Print the labels
for label_code, label in enumerate(labels):
    print(f"{label_code}:'{label}'")
    print(",",end="")

0:'FERRO MANGANESE 75% - 80%'
,1:'FERRO MANGANESE Mn 70% - 75%'
,2:'SILICO MANGANESE DOMESTIC'
,3:'SILICO MANGANESE EXPORT'
,4:'SILICO MANGANESE Mn 60% - 65%'
,5:'SILICO MANGANESE Mn 60% to 65% LOW PHOS'
,6:'SILICO MANGANESE Mn 65% to 70%'
,7:'SILICO MANGANESE Mn 65% to 70% LOW PHOS'
,8:'SILICO MANGANESE Mn BELOW 60%'
,

In [66]:
 df.nunique(axis=0)

QUANTITY    394
region       97
day          31
month        12
cus-mat       9
dtype: int64

In [67]:
from sklearn.preprocessing import LabelEncoder

# Perform label encoding
label_encoder = LabelEncoder()
label_encoder.fit(df['region'])

LabelEncoder()

In [68]:
import pickle
filename = 'label_encoder.pkl'
pickle.dump(label_encoder, open(filename, 'wb'))

In [69]:
df['region'] = label_encoder.transform(df['region'])

In [70]:
labels = label_encoder.classes_
labels

array(['29160-904 - SERRA / ES / BRAZIL', 'ABU DHABI, UAE', 'ABUDHABI',
       'Andhra Pradesh', 'Avenida Brigadeiro Eduardo Gomes,Ba', 'BANGKOK',
       'BANGKOK - THAILAND', 'BELGIUM', 'BELLARY', 'BENGALURE',
       'BHANDARA', 'BHILAI,   DIST DURG', 'BHIWADI - DIST ALWAR',
       'BHIWANDI, THANE', 'CANADA T3L 0C9', 'CHAMARAJPET, BANGALORE',
       'CHENNAI', 'COIMBATORE', 'CUTTACK', 'Chhattisgarh', 'Delhi',
       'Dubai', 'EGYPT', 'ERODE', 'ERODE DT,', 'GENEVA', 'GENOA - ITALY',
       'GERMANY', 'GUMMIDIPOONDI', 'Geneva GE', 'Gujarat', 'HINDUPUR',
       'HINDUPUR MANDAL', 'HINDUPURAM', 'HONG KONG',
       'Hong Kong Island HK', 'ISKENDERUN', 'ISRAEL', 'ISTANBUL, TURKEY',
       'ITALY', 'JAPAN', 'JORDON', 'KINGDOM OF BAHRAIN', 'KOLAR',
       'KOLKATA', 'KOREA', 'KUWAIT', 'Karnataka', 'Kerala',
       'LAKE TOWER, DUBAI', 'LIMASSOL, CYPRUS', 'LONDON', 'MACEDONIA',
       'MEXICO CP', 'MIHIJAM', 'MUMBAI', 'MYSURU (MYSORE)', 'Maharashtra',
       'NAGPUR (MS)', 'NEW DELHI', 'NEW TERRITORIES, HONG KONG',
       'NEW ZEALAND', 'Orissa', 'Outside India OI', 'PARGI',
       'PONDICHERRY', 'Pondicherry', 'RAIPUR', 'ROURKELA', 'Rajasthan',
       'SALEM', 'SHARJAH', 'SHEUNG WAN, HONG KONG', 'SINGAPORE',
       'SOHAR, SULTANATE OF OMAN', 'SOMALWADA - NAGPUR',
       'SRI KALAHASTHI - CHITTOR', 'SWEDEN', 'SWITZERLAND', 'Schwyz SZ',
       'Singapore SG', 'TAIPEI TAIWAN, ROC', 'THAILAND', 'TIRUVALLUR',
       'TOKYO', 'TOKYO - JAPAN', 'TOKYO, JAPAN', 'TUMAKURU', 'TURKEY',
       'Tamil Nadu', 'Telangana', 'Thailand', 'United Kingdom',
       'VISAKHAPATNAM', 'VIZIANAGARAM', 'WANHAI HONGKONG', 'West Bengal'],
      dtype=object)

In [71]:

# Get the labels
labels = label_encoder.classes_

# Print the labels
for label_code, label in enumerate(labels):
    print(f"{label_code}:'{label}'")
    print(",",end="")

0:'29160-904 - SERRA / ES / BRAZIL'
,1:'ABU DHABI, UAE'
,2:'ABUDHABI'
,3:'Andhra Pradesh'
,4:'Avenida Brigadeiro Eduardo Gomes,Ba'
,5:'BANGKOK'
,6:'BANGKOK - THAILAND'
,7:'BELGIUM'
,8:'BELLARY'
,9:'BENGALURE'
,10:'BHANDARA'
,11:'BHILAI,   DIST DURG'
,12:'BHIWADI - DIST ALWAR'
,13:'BHIWANDI, THANE'
,14:'CANADA T3L 0C9'
,15:'CHAMARAJPET, BANGALORE'
,16:'CHENNAI'
,17:'COIMBATORE'
,18:'CUTTACK'
,19:'Chhattisgarh'
,20:'Delhi'
,21:'Dubai'
,22:'EGYPT'
,23:'ERODE'
,24:'ERODE DT,'
,25:'GENEVA'
,26:'GENOA - ITALY'
,27:'GERMANY'
,28:'GUMMIDIPOONDI'
,29:'Geneva GE'
,30:'Gujarat'
,31:'HINDUPUR'
,32:'HINDUPUR MANDAL'
,33:'HINDUPURAM'
,34:'HONG KONG'
,35:'Hong Kong Island HK'
,36:'ISKENDERUN'
,37:'ISRAEL'
,38:'ISTANBUL, TURKEY'
,39:'ITALY'
,40:'JAPAN'
,41:'JORDON'
,42:'KINGDOM OF BAHRAIN'
,43:'KOLAR'
,44:'KOLKATA'
,45:'KOREA'
,46:'KUWAIT'
,47:'Karnataka'
,48:'Kerala'
,49:'LAKE TOWER, DUBAI'
,50:'LIMASSOL, CYPRUS'
,51:'LONDON'
,52:'MACEDONIA'
,53:'MEXICO CP'
,54:'MIHIJAM'
,55:'MUMBAI'
,56:'MYSURU (MYSORE)'
,57:'Maharashtra'
,58:'NAGPUR (MS)'
,59:'NEW DELHI'
,60:'NEW TERRITORIES, HONG KONG'
,61:'NEW ZEALAND'
,62:'Orissa'
,63:'Outside India OI'
,64:'PARGI'
,65:'PONDICHERRY'
,66:'Pondicherry'
,67:'RAIPUR'
,68:'ROURKELA'
,69:'Rajasthan'
,70:'SALEM'
,71:'SHARJAH'
,72:'SHEUNG WAN, HONG KONG'
,73:'SINGAPORE'
,74:'SOHAR, SULTANATE OF OMAN'
,75:'SOMALWADA - NAGPUR'
,76:'SRI KALAHASTHI - CHITTOR'
,77:'SWEDEN'
,78:'SWITZERLAND'
,79:'Schwyz SZ'
,80:'Singapore SG'
,81:'TAIPEI TAIWAN, ROC'
,82:'THAILAND'
,83:'TIRUVALLUR'
,84:'TOKYO'
,85:'TOKYO - JAPAN'
,86:'TOKYO, JAPAN'
,87:'TUMAKURU'
,88:'TURKEY'
,89:'Tamil Nadu'
,90:'Telangana'
,91:'Thailand'
,92:'United Kingdom'
,93:'VISAKHAPATNAM'
,94:'VIZIANAGARAM'
,95:'WANHAI HONGKONG'
,96:'West Bengal'
,

In [72]:
df = df[df['QUANTITY'] >= 0]
df

      QUANTITY  region  day  month  cus-mat
0         25.0       3    5      2        4
1         30.0       3   25      1        4
2         30.0      47    4      3        4
3         30.0      47   24      1        4
4         30.0      47   21      1        4
...        ...     ...  ...    ...      ...
9533      25.0      91   21      4        6
9534      24.0      91    9     10        6
9535      24.0      91    9     10        6
9536      24.0      91    9     10        6
9537      23.0      91    9     10        6

[9396 rows x 5 columns]

In [73]:
x=df.drop('QUANTITY',axis=1)

x

      region  day  month  cus-mat
0          3    5      2        4
1          3   25      1        4
2         47    4      3        4
3         47   24      1        4
4         47   21      1        4
...      ...  ...    ...      ...
9533      91   21      4        6
9534      91    9     10        6
9535      91    9     10        6
9536      91    9     10        6
9537      91    9     10        6

[9396 rows x 4 columns]

In [74]:
y=(df['QUANTITY'].astype(int))
y

0       25
1       30
2       30
3       30
4       30
        ..
9533    25
9534    24
9535    24
9536    24
9537    23
Name: QUANTITY, Length: 9396, dtype: int32

In [75]:
from sklearn.metrics import mean_squared_error

In [76]:
import pandas as pd
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split


# # Assuming your dataset is stored in a DataFrame called 'df'
# # Split the data into training and testing sets (80% train, 20% test)
# train_data, test_data = train_test_split(df, test_size=0.2, random_state=42)

# # Define target variable and feature variables
# y_train = train_data['QUANTITY']
# x_train = train_data[['region', 'Day', 'Month', 'cus-mat']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# Create and train the XGBoost regression model
model = XGBRegressor()
model.fit(x_train, y_train)

# Make predictions on the test set
y_pred = model.predict(df[['region', 'day', 'month', 'cus-mat']])


# Evaluate the model's performance
mse = mean_squared_error(df['QUANTITY'], y_pred)
rmse = mse ** 0.1
print("Root Mean Squared Error (RMSE):", rmse)

Root Mean Squared Error (RMSE): 1.0961697894172466

In [77]:
import pickle

# Save the model to a file
filename = 'xgboost_model.pkl'
pickle.dump(model, open(filename, 'wb'))

In [78]:
df.tail(100)

      QUANTITY  region  day  month  cus-mat
9438      27.0      71    5      8        7
9439      27.0      71    5      8        7
9440      27.0      71    5      8        7
9441      27.0      71    5      8        7
9442      27.0      71    5      8        7
...        ...     ...  ...    ...      ...
9533      25.0      91   21      4        6
9534      24.0      91    9     10        6
9535      24.0      91    9     10        6
9536      24.0      91    9     10        6
9537      23.0      91    9     10        6

[100 rows x 5 columns]

In [79]:
import pickle
import numpy as np
import xgboost as xgb

# Load the XGBoost model from the saved file
with open('xgboost_model.pkl', 'rb') as file:
    model = pickle.load(file)

# Assuming you have a function to preprocess the input data
def preprocess_input(input_data):
    # Add all the features used during training, including 'CUSTOMER' and 'region'
    # Assuming 'month', 'day', 'year', 'encoded_region', 'CUSTOMER', and 'region' are the feature names used during training.
    # Make sure the order of features matches the order used during training.
    return np.array([input_data['cus-mat'], input_data['month'], input_data['day'], input_data['region']])

# Test a single row
def test_single_row(row_data):
    # Preprocess the input row
    processed_row = preprocess_input(row_data)

    # Reshape the data to fit the model's expected input shape (1, num_features)
    processed_row = processed_row.reshape(1, -1)
    print(processed_row)

    # Make predictions
    prediction = model.predict(processed_row)
    return prediction

# Test a single row with your data (provide the row as a dictionary)
input_row = {'cus-mat': 236, 'month': 8, 'day': 5, 'region':71}
result = test_single_row(input_row)

print(f"Predicted Material: {result[0]}")
#27.0	71	5	8	236

[[236   8   5  71]]
Predicted Material: 26.40812873840332

In [80]:
df.columns

Index(['QUANTITY', 'region', 'day', 'month', 'cus-mat'], dtype='object')

In [81]:
region_pkl = pickle.load(open('label_encoder.pkl', 'rb'))
cus_mat_pkl = pickle.load(open('cus-mat.pkl', 'rb'))

In [82]:
region = 'Andhra Pradesh'
re=region_pkl.transform([region])
day = 5
month = 2
# cus = request.form['cus']
# mat = request.form['mat']
cus_mat= 'A ONE ISPAT PVT LTD-SILICO MANGANESE Mn 60% - 65%'
cu=cus_mat_pkl.transform([cus_mat])
data = np.array([[re[0], day, month, cu[0]]])

ValueError: y contains previously unseen labels: 'A ONE ISPAT PVT LTD-SILICO MANGANESE Mn 60% - 65%'

In [83]:
prediction = model.predict(data)

C:\Users\srikanth\anaconda3\lib\site-packages\xgboost\data.py:925: UserWarning: Unknown data type: <class 'dict'>, trying to convert it to csr_matrix
  warnings.warn(

TypeError: Not supported type for data.<class 'dict'>

In [84]:
prediction

NameError: name 'prediction' is not defined

In [85]:
options = [
    'A ONE ISPAT PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'A ONE STEEL AND ALLOYS PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'A ONE STEELS INDIA (PVT) LTD-SILICO MANGANESE  Mn 60% - 65%',
       'A.T.E. MASKATI LTD-FERRO MANGANESE 75% - 80%',
       'AB METALS PTE. LTD-SILICO MANGANESE  Mn 65% to 70%',
       'ACARER METAL SANAYI VE TICARET A.S-SILICO MANGANESE  Mn 60% - 65%',
       'AGARWAL INDUCTION FURNACE PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'AGARWAL INDUCTION FURNACE PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'AGARWAL INDUCTION FURNACE PVT LTD-SILICO MANGANESE  Mn BELOW 60%',
       'AGNI STEELS PRIVATE LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'AGRA CASTINGS PVT LTD-SILICO MANGANESE DOMESTIC',
       'ANJANEY FERRO ALLOYS LTD-SILICO MANGANESE  Mn 65% to 70%',
       'ARABIAN GULF STEEL INDUSTRIES LLC-SILICO MANGANESE  Mn 60% - 65%',
       'ARABIAN GULF STEEL INDUSTRIES LLC-SILICO MANGANESE  Mn 65% to 70%',
       'ARABIAN GULF STEEL INDUSTRIES LLC-SILICO MANGANESE DOMESTIC',
       'ARCELORMITTAL BRASIL S/A-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'ARCELORMITTAL COMERCIO EXTERIOR S/A-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'ASIA MINERALS LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'ASIA MINERALS LIMITED-SILICO MANGANESE EXPORT',
       'AVEKS (SUISSE) S A-SILICO MANGANESE  Mn 60% - 65%',
       'AVEKS (SUISSE) S A-SILICO MANGANESE  Mn 65% to 70%',
       'AVEKS (SUISSE) S A-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'AVEKS (SUISSE) S A-SILICO MANGANESE DOMESTIC',
       'AVEKS (SUISSE) S A-SILICO MANGANESE EXPORT',
       'B B MINERALS AND METALS-SILICO MANGANESE  Mn 60% - 65%',
       'B B MINERALS AND METALS-SILICO MANGANESE  Mn 65% to 70%',
       'BAHUBALI OVERSEAS-SILICO MANGANESE DOMESTIC',
       'BARBIL MINING AND INDUSTRIES PVT LI-SILICO MANGANESE  Mn 60% - 65%',
       'CHARISMA RESOURCES LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'CHARISMA RESOURCES LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'CONCORDIA RESOURCES LIMITED-FERRO MANGANESE 75% - 80%',
       'CONCORDIA RESOURCES LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'CONCORDIA RESOURCES LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'CONCORDIA RESOURCES LIMITED-SILICO MANGANESE DOMESTIC',
       'CONCORDIA RESOURCES LIMITED-SILICO MANGANESE EXPORT',
       'D S ALLOYD PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'D S ALLOYD PVT LTD-SILICO MANGANESE DOMESTIC',
       'DAHUTI INTERNATIONAL LIMITED-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'DIVIJ ASSOCIATE PTE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'DUFERCO ASIA PTE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'DUFERCO SA-SILICO MANGANESE  Mn 65% to 70%',
       'EKAGRATA ENTERPRISES PTE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'EL MARAKBY STEEL-SILICO MANGANESE EXPORT',
       'ELMET SA de CV-FERRO MANGANESE 75% - 80%',
       'EMIRATES STEEL INDUSTRIES PJSC-FERRO MANGANESE 75% - 80%',
       'EMIRATES STEEL INDUSTRIES PJSC-SILICO MANGANESE  Mn 65% to 70%',
       'EMIRATES STEEL INDUSTRIES PJSC-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'EMIRATES STEEL INDUSTRIES PJSC-SILICO MANGANESE EXPORT',
       'EREGLI DEMIR VE CELIK FABRIKALARI T-SILICO MANGANESE  Mn 65% to 70%',
       'EXCELCO CORPORATION-SILICO MANGANESE  Mn 60% - 65%',
       'EXCELCO CORPORATION-SILICO MANGANESE  Mn 65% to 70%',
       'FELMAN TRADING EUROPE AG-SILICO MANGANESE  Mn 65% to 70%',
       'FORSTEEL SRL-SILICO MANGANESE  Mn 65% to 70%',
       'GALMET S.P.A.-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'GBF BONTEX TAIWAN INC-SILICO MANGANESE  Mn 60% - 65%',
       'GBF BONTEX TAIWAN INC-SILICO MANGANESE  Mn 65% to 70%',
       'GBF BONTEX TAIWAN INC-SILICO MANGANESE DOMESTIC',
       'GBF BONTEX TAIWAN INC-SILICO MANGANESE EXPORT',
       'GLENCORE INTERNATIONAL AG-SILICO MANGANESE  Mn 65% to 70%',
       'GLOBAL PRATEK PTE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'GME METALS SRL-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'GMI COMMODITIES AB-SILICO MANGANESE  Mn 60% - 65%',
       'GMI COMMODITIES AB-SILICO MANGANESE  Mn 65% to 70%',
       'GMI COMMODITIES AB-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'GOYAL ENERGY AND STEEL PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'GRETA METAL PTE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'GRETA METAL PTE LTD-SILICO MANGANESE EXPORT',
       'HANWA CO LTD-SILICO MANGANESE  Mn 65% to 70%',
       'HANWA CO LTD-SILICO MANGANESE EXPORT',
       'HOJIN IND CO LTD-SILICO MANGANESE DOMESTIC',
       'ICDAS CELIK ENERJI TERSANE VE ULASI-SILICO MANGANESE  Mn 65% to 70%',
       'ICON FERRO ALLOYS-SILICO MANGANESE  Mn 60% - 65%',
       'ICON FERRO ALLOYS-SILICO MANGANESE  Mn BELOW 60%',
       'IMETALS GROUP TRADING DWC LLC-SILICO MANGANESE EXPORT',
       'INDUSTRIAL METALLURGICAL SOLUTIONS-SILICO MANGANESE  Mn 65% to 70%',
       'INDUSTRIAL METALLURGICAL SOLUTIONS-SILICO MANGANESE EXPORT',
       'INNOVATION WORLDWIDE DMCC-SILICO MANGANESE  Mn 65% to 70%',
       'INNOVATION WORLDWIDE DMCC-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'INNOVATION WORLDWIDE DMCC-SILICO MANGANESE EXPORT',
       'INTERNATIONAL METALLURGICAL GROUP-SILICO MANGANESE  Mn 65% to 70%',
       'INTERTRADE KOMPANI-SILICO MANGANESE  Mn 60% - 65%',
       'INTERTRADE KOMPANI-SILICO MANGANESE  Mn 65% to 70%',
       'ISKENDERUN DEMIR VE CELIK A S-SILICO MANGANESE  Mn 65% to 70%',
       'ISKENDERUN IRON & STEEL CO.-FERRO MANGANESE 75% - 80%',
       'JAI HIND WIRE ROD MILLS PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'JAI HIND WIRE ROD MILLS PVT LTD-SILICO MANGANESE DOMESTIC',
       'JAI HIND WIRE ROD MILLS PVT LTD-SILICO MANGANESE EXPORT',
       'JAYA SAKTHI CASTING INDIA PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'JFE SOHJI CORPORATION-FERRO MANGANESE 75% - 80%',
       'JFE SOHJI CORPORATION-SILICO MANGANESE  Mn 60% - 65%',
       'JFE SOHJI CORPORATION-SILICO MANGANESE  Mn 65% to 70%',
       'JINDAL SHADEED IRON & STEEL CO LLC-SILICO MANGANESE  Mn 65% to 70%',
       'KAIZEN COLD FORMED STEEL PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'KAIZEN COLD FORMED STEEL PVT LTD-SILICO MANGANESE  Mn BELOW 60%',
       'KAMACHI INDUSTRIES LIMITED(SMD DIV)-SILICO MANGANESE  Mn 60% - 65%',
       'KAMACHI INDUSTRIES LIMITED(SMD DIV)-SILICO MANGANESE DOMESTIC',
       'KANIKA ISPAT PRIVATE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'KAY BEE ALLOYS AND METALS-SILICO MANGANESE  Mn 60% - 65%',
       'KAY BEE ALLOYS AND METALS-SILICO MANGANESE  Mn 65% to 70%',
       'KAY BEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE  Mn 60% - 65%',
       'KAY BEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE DOMESTIC',
       'KAY BEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE EXPORT',
       'KAYBEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE  Mn 60% - 65%',
       'KAYBEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE  Mn 65% to 70%',
       'KAYBEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE DOMESTIC',
       'KEVIN STEELS PVT LTD-SILICO MANGANESE DOMESTIC',
       'KHAYATI STEEL INDUSTRIES PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'KHAYATI STEEL INDUSTRIES PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'KHAYATI STEEL INDUSTRIES PVT LTD-SILICO MANGANESE  Mn BELOW 60%',
       'KUSHAL CHEMICALS-SILICO MANGANESE  Mn 60% - 65%',
       'KUSHAL CHEMICALS-SILICO MANGANESE  Mn 65% to 70%',
       'L & Y ASIA PACIFIC LTD-SILICO MANGANESE  Mn 65% to 70%',
       'L & Y ASIA PACIFIC LTD-SILICO MANGANESE DOMESTIC',
       'L & Y ASIA PACIFIC LTD-SILICO MANGANESE EXPORT',
       'LAMED INVESTMENT AND TRADE CO LTD-SILICO MANGANESE  Mn 65% to 70%',
       'LEMETCO GMBH-SILICO MANGANESE  Mn 60% - 65%',
       'LEMETCO GMBH-SILICO MANGANESE  Mn 65% to 70%',
       'LEMETCO GMBH-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'LEO OVERSEAS-SILICO MANGANESE  Mn 65% to 70%',
       'LOTUS STEELS-SILICO MANGANESE  Mn BELOW 60%',
       'MAA MAHAMAYA INDUSTRIES LTD-SILICO MANGANESE  Mn 60% - 65%',
       'MAA MAHAMAYA INDUSTRIES LTD-SILICO MANGANESE DOMESTIC',
       'MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE  Mn BELOW 60%',
       'MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE DOMESTIC',
       'MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE  Mn 60% - 65%',
       'MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE DOMESTIC',
       'MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE EXPORT',
       'MANAGER (STORES) RECEIPTS, PS-II-SILICO MANGANESE  Mn 60% - 65%',
       'MANAGER (STORES) RECEIPTS, PS-II-SILICO MANGANESE DOMESTIC',
       'MEENAKSHI STEELS-SILICO MANGANESE DOMESTIC',
       'MEENAKSHI UDYOG (INDIA) PVT LTD-SILICO MANGANESE DOMESTIC',
       'METAL IMPEX-SILICO MANGANESE  Mn 60% - 65%',
       'METALLEGHE SPA-SILICO MANGANESE  Mn 60% - 65%',
       'METALLEGHE SPA-SILICO MANGANESE  Mn 65% to 70%',
       'METALLIC FERRO ALLOYS LLP-SILICO MANGANESE  Mn 65% to 70%',
       'MIL STEEL AND POWER LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'MIL STEEL AND POWER LIMITED-SILICO MANGANESE EXPORT',
       'MILLION LINK (CHINA) INVESTMENT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'MILLION LINK (CHINA) INVESTMENT LTD-SILICO MANGANESE DOMESTIC',
       'MILLION LINK (CHINA) INVESTMENT LTD-SILICO MANGANESE EXPORT',
       'MITSUI & CO LTD-SILICO MANGANESE  Mn 65% to 70%',
       'MITSUI & CO LTD-SILICO MANGANESE EXPORT',
       'MOHAMED ALI ABD EL GHANY-FERRO MANGANESE Mn 70% - 75%',
       'MORTEX INDIA-SILICO MANGANESE  Mn 65% to 70%',
       'MRIDUL STEEL COMPANY-SILICO MANGANESE  Mn 60% - 65%',
       'MRIDUL STEEL COMPANY-SILICO MANGANESE  Mn 65% to 70%',
       'MRIDUL STEEL COMPANY-SILICO MANGANESE  Mn BELOW 60%',
       'MRIDUL STEEL COMPANY-SILICO MANGANESE DOMESTIC',
       'MRIDUL STEEL COMPANY-SILICO MANGANESE EXPORT',
       'MTALX-SILICO MANGANESE  Mn 60% - 65%',
       'MTALX-SILICO MANGANESE  Mn 65% to 70%',
       'NAGPUR MINERALS & CHEMICALS-SILICO MANGANESE  Mn 65% to 70%',
       'NAGPUR MINERALS AND CHEMICALS-SILICO MANGANESE  Mn 60% - 65%',
       'NIPPON STEEL TRADING CORPORATION-SILICO MANGANESE  Mn 65% to 70%',
       'NORECOM LIMITED-FERRO MANGANESE 75% - 80%',
       'NORECOM LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'OSWAL MINERALS LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'PLATINUM STEELS-SILICO MANGANESE  Mn BELOW 60%',
       'PREMIER INDUSTRIAL CORPORATION LTD-SILICO MANGANESE  Mn 65% to 70%',
       'PREMIER INDUSTRIAL CORPORATION LTD-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'PULKIT METALS PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'PULKIT METALS PVT LTD-SILICO MANGANESE DOMESTIC',
       'PUSHPIT STEELS PRIVATE LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'PUSHPIT STEELS PRIVATE LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'PUSHPIT STEELS PRIVATE LIMITED-SILICO MANGANESE DOMESTIC',
       'RAJ TRADERS-SILICO MANGANESE  Mn 60% - 65%',
       'RAJ TRADERS-SILICO MANGANESE  Mn 65% to 70%',
       'RAJ TRADERS-SILICO MANGANESE  Mn BELOW 60%',
       'RAMA HI-POWER TECH-SILICO MANGANESE  Mn 65% to 70%',
       'RAMA HI-POWER TECH-SILICO MANGANESE DOMESTIC',
       'RDTMT STEELS INDIA PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'RONLY LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'RONLY LIMITED-SILICO MANGANESE  Mn 65% to 70% LOW PHOS',
       'S.R.S STEEL PRIVATE LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'S.R.S STEEL PRIVATE LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'SANTAS FAR EAST COMPANY-SILICO MANGANESE  Mn 65% to 70%',
       'SARDA ENERGY & MINERALS LTD.-SILICO MANGANESE  Mn 65% to 70%',
       'SARITA METAL & ALLOYS-SILICO MANGANESE  Mn 60% - 65%',
       'SARITA METAL & ALLOYS-SILICO MANGANESE DOMESTIC',
       'SENTUO STEEL LIMITED-SILICO MANGANESE  Mn 65% to 70%',
       'SENTUO STEEL LIMITED-SILICO MANGANESE EXPORT',
       'SHREEYAM POWER & STEEL INDUSTRIES L-SILICO MANGANESE  Mn 60% to 65% LOW PHOS',
       'SHRI TIRUPATI STEEL CAST LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'SHRI TIRUPATI STEEL CAST LIMITED-SILICO MANGANESE DOMESTIC',
       'SIAM YAMATO STEEL CO LTD-SILICO MANGANESE  Mn 65% to 70%',
       'SIDENAL-SILICO MANGANESE  Mn 65% to 70%',
       'SR MANAGER FINANCE - RAW MATERIAL-SILICO MANGANESE  Mn 60% to 65% LOW PHOS',
       'SREE RENGARAAJ STEEL AND ALLOYS PVT-SILICO MANGANESE  Mn 65% to 70%',
       'SREE RENGARAAJ STEEL AND ALLOYS PVT-SILICO MANGANESE EXPORT',
       'SREE RENGARAJ ISPAT INDUSTRIES PVT-SILICO MANGANESE  Mn 60% - 65%',
       'SREE RENGARAJ ISPAT INDUSTRIES PVT-SILICO MANGANESE  Mn 65% to 70%',
       'SREE RENGARAJ ISPAT INDUSTRIES PVT-SILICO MANGANESE DOMESTIC',
       'SRG MINERALS & METALS-SILICO MANGANESE  Mn 60% - 65%',
       'SRG MINERALS & METALS-SILICO MANGANESE  Mn 65% to 70%',
       'SRG MINERALS & METALS-SILICO MANGANESE EXPORT',
       'SRS ISPATT PRIVATE LIMITED - SALEM-SILICO MANGANESE  Mn 60% - 65%',
       'SRS ISPATT PRIVATE LIMITED - SALEM-SILICO MANGANESE  Mn 65% to 70%',
       'SRS ISPATT PRIVATE LIMITED - SALEM-SILICO MANGANESE  Mn BELOW 60%',
       'SSCA FUELS PRIVATE LIMITED-SILICO MANGANESE  Mn BELOW 60%',
       'STAIN LESS METALS GENERAL TRADING F-SILICO MANGANESE EXPORT',
       'STEELCO FOR STEEL TRADING-SILICO MANGANESE  Mn 65% to 70%',
       'STEELFORCE NV-SILICO MANGANESE  Mn 60% - 65%',
       'STEELFORCE NV-SILICO MANGANESE  Mn 65% to 70%',
       'STEMCOR (S.E.A) PTE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'SUGNA METALS LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'SULB COMPANY B S C CLOSED-SILICO MANGANESE  Mn 65% to 70%',
       'SUN TALENT INDUSTRIAL CO LTD-SILICO MANGANESE  Mn 65% to 70%',
       'SURYADEV ALLOYS & POWER PVT LTD-SILICO MANGANESE DOMESTIC',
       'TA CORPORATION PVT LTD-SILICO MANGANESE DOMESTIC',
       'TARSUN STEELS INDIA PRIVATE LIMITED-SILICO MANGANESE DOMESTIC',
       'TUF METALLURGICAL PVT LTD-SILICO MANGANESE  Mn 65% to 70%',
       'TYVIN INTERNATION CO LTD-SILICO MANGANESE  Mn 65% to 70%',
       'UDDISH ISPAT-SILICO MANGANESE  Mn 60% - 65%',
       'UJJWAL TRADE LINK-SILICO MANGANESE  Mn 60% - 65%',
       'UJJWAL TRADE LINK-SILICO MANGANESE  Mn 65% to 70%',
       'UJJWAL TRADE LINK-SILICO MANGANESE DOMESTIC',
       'UJJWAL TRADE LINK-SILICO MANGANESE EXPORT',
       'UMC METALS LTD-SILICO MANGANESE  Mn 65% to 70%',
       'UNI METAL CO LTD-SILICO MANGANESE  Mn 60% - 65%',
       'UNITED STEEL INDUSTRIAL COMPANY(K S-SILICO MANGANESE  Mn 65% to 70%',
       'UNIVERSAL HI-TECH EQUIPMENTS FZE-SILICO MANGANESE DOMESTIC',
       'VAMANCORE PTE LTD-SILICO MANGANESE  Mn 65% to 70%',
       'VEDIKA METALS PVT LTD-SILICO MANGANESE  Mn BELOW 60%',
       'VGK STEELS-SILICO MANGANESE  Mn 60% - 65%',
       'VGK STEELS-SILICO MANGANESE  Mn 65% to 70%',
       'VIMET AG-SILICO MANGANESE  Mn 65% to 70%',
       'VINAYAK STEELS LIMITED-SILICO MANGANESE  Mn 60% - 65%',
       'VINAYAK STEELS LIMITED-SILICO MANGANESE DOMESTIC',
       'VRKP SPONGE AND POWER PLANT LLP-SILICO MANGANESE  Mn 60% - 65%',
       'VRKP SPONGE AND POWER PLANT LLP-SILICO MANGANESE  Mn 65% to 70%',
       'WORLD METALS & ALLOYS FZC-FERRO MANGANESE 75% - 80%',
       'WORLD METALS & ALLOYS FZC-SILICO MANGANESE  Mn 60% - 65%',
       'WORLD METALS & ALLOYS FZC-SILICO MANGANESE  Mn 65% to 70%',
       'WORLD METALS & ALLOYS FZC-SILICO MANGANESE  Mn 65% to 70% LOW PHOS'    
]

html_options = ''.join([f'<option>{option}</option>\n' for option in options])

print(html_options)

<option>A ONE ISPAT PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>A ONE STEEL AND ALLOYS PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>A ONE STEELS INDIA (PVT) LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>A.T.E. MASKATI LTD-FERRO MANGANESE 75% - 80%</option>
<option>AB METALS PTE. LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>ACARER METAL SANAYI VE TICARET A.S-SILICO MANGANESE  Mn 60% - 65%</option>
<option>AGARWAL INDUCTION FURNACE PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>AGARWAL INDUCTION FURNACE PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>AGARWAL INDUCTION FURNACE PVT LTD-SILICO MANGANESE  Mn BELOW 60%</option>
<option>AGNI STEELS PRIVATE LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>AGRA CASTINGS PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>ANJANEY FERRO ALLOYS LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>ARABIAN GULF STEEL INDUSTRIES LLC-SILICO MANGANESE  Mn 60% - 65%</option>
<option>ARABIAN GULF STEEL INDUSTRIES LLC-SILICO MANGANESE  Mn 65% to 70%</option>
<option>ARABIAN GULF STEEL INDUSTRIES LLC-SILICO MANGANESE DOMESTIC</option>
<option>ARCELORMITTAL BRASIL S/A-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>ARCELORMITTAL COMERCIO EXTERIOR S/A-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>ASIA MINERALS LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>ASIA MINERALS LIMITED-SILICO MANGANESE EXPORT</option>
<option>AVEKS (SUISSE) S A-SILICO MANGANESE  Mn 60% - 65%</option>
<option>AVEKS (SUISSE) S A-SILICO MANGANESE  Mn 65% to 70%</option>
<option>AVEKS (SUISSE) S A-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>AVEKS (SUISSE) S A-SILICO MANGANESE DOMESTIC</option>
<option>AVEKS (SUISSE) S A-SILICO MANGANESE EXPORT</option>
<option>B B MINERALS AND METALS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>B B MINERALS AND METALS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>BAHUBALI OVERSEAS-SILICO MANGANESE DOMESTIC</option>
<option>BARBIL MINING AND INDUSTRIES PVT LI-SILICO MANGANESE  Mn 60% - 65%</option>
<option>CHARISMA RESOURCES LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>CHARISMA RESOURCES LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>CONCORDIA RESOURCES LIMITED-FERRO MANGANESE 75% - 80%</option>
<option>CONCORDIA RESOURCES LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>CONCORDIA RESOURCES LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>CONCORDIA RESOURCES LIMITED-SILICO MANGANESE DOMESTIC</option>
<option>CONCORDIA RESOURCES LIMITED-SILICO MANGANESE EXPORT</option>
<option>D S ALLOYD PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>D S ALLOYD PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>DAHUTI INTERNATIONAL LIMITED-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>DIVIJ ASSOCIATE PTE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>DUFERCO ASIA PTE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>DUFERCO SA-SILICO MANGANESE  Mn 65% to 70%</option>
<option>EKAGRATA ENTERPRISES PTE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>EL MARAKBY STEEL-SILICO MANGANESE EXPORT</option>
<option>ELMET SA de CV-FERRO MANGANESE 75% - 80%</option>
<option>EMIRATES STEEL INDUSTRIES PJSC-FERRO MANGANESE 75% - 80%</option>
<option>EMIRATES STEEL INDUSTRIES PJSC-SILICO MANGANESE  Mn 65% to 70%</option>
<option>EMIRATES STEEL INDUSTRIES PJSC-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>EMIRATES STEEL INDUSTRIES PJSC-SILICO MANGANESE EXPORT</option>
<option>EREGLI DEMIR VE CELIK FABRIKALARI T-SILICO MANGANESE  Mn 65% to 70%</option>
<option>EXCELCO CORPORATION-SILICO MANGANESE  Mn 60% - 65%</option>
<option>EXCELCO CORPORATION-SILICO MANGANESE  Mn 65% to 70%</option>
<option>FELMAN TRADING EUROPE AG-SILICO MANGANESE  Mn 65% to 70%</option>
<option>FORSTEEL SRL-SILICO MANGANESE  Mn 65% to 70%</option>
<option>GALMET S.P.A.-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>GBF BONTEX TAIWAN INC-SILICO MANGANESE  Mn 60% - 65%</option>
<option>GBF BONTEX TAIWAN INC-SILICO MANGANESE  Mn 65% to 70%</option>
<option>GBF BONTEX TAIWAN INC-SILICO MANGANESE DOMESTIC</option>
<option>GBF BONTEX TAIWAN INC-SILICO MANGANESE EXPORT</option>
<option>GLENCORE INTERNATIONAL AG-SILICO MANGANESE  Mn 65% to 70%</option>
<option>GLOBAL PRATEK PTE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>GME METALS SRL-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>GMI COMMODITIES AB-SILICO MANGANESE  Mn 60% - 65%</option>
<option>GMI COMMODITIES AB-SILICO MANGANESE  Mn 65% to 70%</option>
<option>GMI COMMODITIES AB-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>GOYAL ENERGY AND STEEL PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>GRETA METAL PTE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>GRETA METAL PTE LTD-SILICO MANGANESE EXPORT</option>
<option>HANWA CO LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>HANWA CO LTD-SILICO MANGANESE EXPORT</option>
<option>HOJIN IND CO LTD-SILICO MANGANESE DOMESTIC</option>
<option>ICDAS CELIK ENERJI TERSANE VE ULASI-SILICO MANGANESE  Mn 65% to 70%</option>
<option>ICON FERRO ALLOYS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>ICON FERRO ALLOYS-SILICO MANGANESE  Mn BELOW 60%</option>
<option>IMETALS GROUP TRADING DWC LLC-SILICO MANGANESE EXPORT</option>
<option>INDUSTRIAL METALLURGICAL SOLUTIONS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>INDUSTRIAL METALLURGICAL SOLUTIONS-SILICO MANGANESE EXPORT</option>
<option>INNOVATION WORLDWIDE DMCC-SILICO MANGANESE  Mn 65% to 70%</option>
<option>INNOVATION WORLDWIDE DMCC-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>INNOVATION WORLDWIDE DMCC-SILICO MANGANESE EXPORT</option>
<option>INTERNATIONAL METALLURGICAL GROUP-SILICO MANGANESE  Mn 65% to 70%</option>
<option>INTERTRADE KOMPANI-SILICO MANGANESE  Mn 60% - 65%</option>
<option>INTERTRADE KOMPANI-SILICO MANGANESE  Mn 65% to 70%</option>
<option>ISKENDERUN DEMIR VE CELIK A S-SILICO MANGANESE  Mn 65% to 70%</option>
<option>ISKENDERUN IRON & STEEL CO.-FERRO MANGANESE 75% - 80%</option>
<option>JAI HIND WIRE ROD MILLS PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>JAI HIND WIRE ROD MILLS PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>JAI HIND WIRE ROD MILLS PVT LTD-SILICO MANGANESE EXPORT</option>
<option>JAYA SAKTHI CASTING INDIA PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>JFE SOHJI CORPORATION-FERRO MANGANESE 75% - 80%</option>
<option>JFE SOHJI CORPORATION-SILICO MANGANESE  Mn 60% - 65%</option>
<option>JFE SOHJI CORPORATION-SILICO MANGANESE  Mn 65% to 70%</option>
<option>JINDAL SHADEED IRON & STEEL CO LLC-SILICO MANGANESE  Mn 65% to 70%</option>
<option>KAIZEN COLD FORMED STEEL PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>KAIZEN COLD FORMED STEEL PVT LTD-SILICO MANGANESE  Mn BELOW 60%</option>
<option>KAMACHI INDUSTRIES LIMITED(SMD DIV)-SILICO MANGANESE  Mn 60% - 65%</option>
<option>KAMACHI INDUSTRIES LIMITED(SMD DIV)-SILICO MANGANESE DOMESTIC</option>
<option>KANIKA ISPAT PRIVATE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>KAY BEE ALLOYS AND METALS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>KAY BEE ALLOYS AND METALS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>KAY BEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>KAY BEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE DOMESTIC</option>
<option>KAY BEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE EXPORT</option>
<option>KAYBEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>KAYBEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>KAYBEE INDUSTRIAL ALLOYS (P) LTD-SILICO MANGANESE DOMESTIC</option>
<option>KEVIN STEELS PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>KHAYATI STEEL INDUSTRIES PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>KHAYATI STEEL INDUSTRIES PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>KHAYATI STEEL INDUSTRIES PVT LTD-SILICO MANGANESE  Mn BELOW 60%</option>
<option>KUSHAL CHEMICALS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>KUSHAL CHEMICALS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>L & Y ASIA PACIFIC LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>L & Y ASIA PACIFIC LTD-SILICO MANGANESE DOMESTIC</option>
<option>L & Y ASIA PACIFIC LTD-SILICO MANGANESE EXPORT</option>
<option>LAMED INVESTMENT AND TRADE CO LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>LEMETCO GMBH-SILICO MANGANESE  Mn 60% - 65%</option>
<option>LEMETCO GMBH-SILICO MANGANESE  Mn 65% to 70%</option>
<option>LEMETCO GMBH-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>LEO OVERSEAS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>LOTUS STEELS-SILICO MANGANESE  Mn BELOW 60%</option>
<option>MAA MAHAMAYA INDUSTRIES LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>MAA MAHAMAYA INDUSTRIES LTD-SILICO MANGANESE DOMESTIC</option>
<option>MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE  Mn BELOW 60%</option>
<option>MAALU FERRO ALLOYS PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>MAHRISHI ALLOYS PVT LTD-SILICO MANGANESE EXPORT</option>
<option>MANAGER (STORES) RECEIPTS, PS-II-SILICO MANGANESE  Mn 60% - 65%</option>
<option>MANAGER (STORES) RECEIPTS, PS-II-SILICO MANGANESE DOMESTIC</option>
<option>MEENAKSHI STEELS-SILICO MANGANESE DOMESTIC</option>
<option>MEENAKSHI UDYOG (INDIA) PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>METAL IMPEX-SILICO MANGANESE  Mn 60% - 65%</option>
<option>METALLEGHE SPA-SILICO MANGANESE  Mn 60% - 65%</option>
<option>METALLEGHE SPA-SILICO MANGANESE  Mn 65% to 70%</option>
<option>METALLIC FERRO ALLOYS LLP-SILICO MANGANESE  Mn 65% to 70%</option>
<option>MIL STEEL AND POWER LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>MIL STEEL AND POWER LIMITED-SILICO MANGANESE EXPORT</option>
<option>MILLION LINK (CHINA) INVESTMENT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>MILLION LINK (CHINA) INVESTMENT LTD-SILICO MANGANESE DOMESTIC</option>
<option>MILLION LINK (CHINA) INVESTMENT LTD-SILICO MANGANESE EXPORT</option>
<option>MITSUI & CO LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>MITSUI & CO LTD-SILICO MANGANESE EXPORT</option>
<option>MOHAMED ALI ABD EL GHANY-FERRO MANGANESE Mn 70% - 75%</option>
<option>MORTEX INDIA-SILICO MANGANESE  Mn 65% to 70%</option>
<option>MRIDUL STEEL COMPANY-SILICO MANGANESE  Mn 60% - 65%</option>
<option>MRIDUL STEEL COMPANY-SILICO MANGANESE  Mn 65% to 70%</option>
<option>MRIDUL STEEL COMPANY-SILICO MANGANESE  Mn BELOW 60%</option>
<option>MRIDUL STEEL COMPANY-SILICO MANGANESE DOMESTIC</option>
<option>MRIDUL STEEL COMPANY-SILICO MANGANESE EXPORT</option>
<option>MTALX-SILICO MANGANESE  Mn 60% - 65%</option>
<option>MTALX-SILICO MANGANESE  Mn 65% to 70%</option>
<option>NAGPUR MINERALS & CHEMICALS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>NAGPUR MINERALS AND CHEMICALS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>NIPPON STEEL TRADING CORPORATION-SILICO MANGANESE  Mn 65% to 70%</option>
<option>NORECOM LIMITED-FERRO MANGANESE 75% - 80%</option>
<option>NORECOM LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>OSWAL MINERALS LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>PLATINUM STEELS-SILICO MANGANESE  Mn BELOW 60%</option>
<option>PREMIER INDUSTRIAL CORPORATION LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>PREMIER INDUSTRIAL CORPORATION LTD-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>PULKIT METALS PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>PULKIT METALS PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>PUSHPIT STEELS PRIVATE LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>PUSHPIT STEELS PRIVATE LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>PUSHPIT STEELS PRIVATE LIMITED-SILICO MANGANESE DOMESTIC</option>
<option>RAJ TRADERS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>RAJ TRADERS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>RAJ TRADERS-SILICO MANGANESE  Mn BELOW 60%</option>
<option>RAMA HI-POWER TECH-SILICO MANGANESE  Mn 65% to 70%</option>
<option>RAMA HI-POWER TECH-SILICO MANGANESE DOMESTIC</option>
<option>RDTMT STEELS INDIA PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>RONLY LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>RONLY LIMITED-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>
<option>S.R.S STEEL PRIVATE LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>S.R.S STEEL PRIVATE LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SANTAS FAR EAST COMPANY-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SARDA ENERGY & MINERALS LTD.-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SARITA METAL & ALLOYS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>SARITA METAL & ALLOYS-SILICO MANGANESE DOMESTIC</option>
<option>SENTUO STEEL LIMITED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SENTUO STEEL LIMITED-SILICO MANGANESE EXPORT</option>
<option>SHREEYAM POWER & STEEL INDUSTRIES L-SILICO MANGANESE  Mn 60% to 65% LOW PHOS</option>
<option>SHRI TIRUPATI STEEL CAST LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>SHRI TIRUPATI STEEL CAST LIMITED-SILICO MANGANESE DOMESTIC</option>
<option>SIAM YAMATO STEEL CO LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SIDENAL-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SR MANAGER FINANCE - RAW MATERIAL-SILICO MANGANESE  Mn 60% to 65% LOW PHOS</option>
<option>SREE RENGARAAJ STEEL AND ALLOYS PVT-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SREE RENGARAAJ STEEL AND ALLOYS PVT-SILICO MANGANESE EXPORT</option>
<option>SREE RENGARAJ ISPAT INDUSTRIES PVT-SILICO MANGANESE  Mn 60% - 65%</option>
<option>SREE RENGARAJ ISPAT INDUSTRIES PVT-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SREE RENGARAJ ISPAT INDUSTRIES PVT-SILICO MANGANESE DOMESTIC</option>
<option>SRG MINERALS & METALS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>SRG MINERALS & METALS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SRG MINERALS & METALS-SILICO MANGANESE EXPORT</option>
<option>SRS ISPATT PRIVATE LIMITED - SALEM-SILICO MANGANESE  Mn 60% - 65%</option>
<option>SRS ISPATT PRIVATE LIMITED - SALEM-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SRS ISPATT PRIVATE LIMITED - SALEM-SILICO MANGANESE  Mn BELOW 60%</option>
<option>SSCA FUELS PRIVATE LIMITED-SILICO MANGANESE  Mn BELOW 60%</option>
<option>STAIN LESS METALS GENERAL TRADING F-SILICO MANGANESE EXPORT</option>
<option>STEELCO FOR STEEL TRADING-SILICO MANGANESE  Mn 65% to 70%</option>
<option>STEELFORCE NV-SILICO MANGANESE  Mn 60% - 65%</option>
<option>STEELFORCE NV-SILICO MANGANESE  Mn 65% to 70%</option>
<option>STEMCOR (S.E.A) PTE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SUGNA METALS LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>SULB COMPANY B S C CLOSED-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SUN TALENT INDUSTRIAL CO LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>SURYADEV ALLOYS & POWER PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>TA CORPORATION PVT LTD-SILICO MANGANESE DOMESTIC</option>
<option>TARSUN STEELS INDIA PRIVATE LIMITED-SILICO MANGANESE DOMESTIC</option>
<option>TUF METALLURGICAL PVT LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>TYVIN INTERNATION CO LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>UDDISH ISPAT-SILICO MANGANESE  Mn 60% - 65%</option>
<option>UJJWAL TRADE LINK-SILICO MANGANESE  Mn 60% - 65%</option>
<option>UJJWAL TRADE LINK-SILICO MANGANESE  Mn 65% to 70%</option>
<option>UJJWAL TRADE LINK-SILICO MANGANESE DOMESTIC</option>
<option>UJJWAL TRADE LINK-SILICO MANGANESE EXPORT</option>
<option>UMC METALS LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>UNI METAL CO LTD-SILICO MANGANESE  Mn 60% - 65%</option>
<option>UNITED STEEL INDUSTRIAL COMPANY(K S-SILICO MANGANESE  Mn 65% to 70%</option>
<option>UNIVERSAL HI-TECH EQUIPMENTS FZE-SILICO MANGANESE DOMESTIC</option>
<option>VAMANCORE PTE LTD-SILICO MANGANESE  Mn 65% to 70%</option>
<option>VEDIKA METALS PVT LTD-SILICO MANGANESE  Mn BELOW 60%</option>
<option>VGK STEELS-SILICO MANGANESE  Mn 60% - 65%</option>
<option>VGK STEELS-SILICO MANGANESE  Mn 65% to 70%</option>
<option>VIMET AG-SILICO MANGANESE  Mn 65% to 70%</option>
<option>VINAYAK STEELS LIMITED-SILICO MANGANESE  Mn 60% - 65%</option>
<option>VINAYAK STEELS LIMITED-SILICO MANGANESE DOMESTIC</option>
<option>VRKP SPONGE AND POWER PLANT LLP-SILICO MANGANESE  Mn 60% - 65%</option>
<option>VRKP SPONGE AND POWER PLANT LLP-SILICO MANGANESE  Mn 65% to 70%</option>
<option>WORLD METALS & ALLOYS FZC-FERRO MANGANESE 75% - 80%</option>
<option>WORLD METALS & ALLOYS FZC-SILICO MANGANESE  Mn 60% - 65%</option>
<option>WORLD METALS & ALLOYS FZC-SILICO MANGANESE  Mn 65% to 70%</option>
<option>WORLD METALS & ALLOYS FZC-SILICO MANGANESE  Mn 65% to 70% LOW PHOS</option>

In [86]:
options1[
   ' ABUDHABI',
' BELLARY',
' BENGALURE',
' BHANDARA',
' BHILAI,   DIST DURG',
' BHIWADI - DIST ALWAR',
' BHIWANDI, THANE',
' CHAMARAJPET, BANGALORE',
' CHENNAI',
' COIMBATORE',
' CUTTACK',
' ERODE',
' ERODE DT,',
' GUMMIDIPOONDI',
' HINDUPUR',
' HINDUPUR MANDAL',
' HINDUPURAM',
' KOLAR',
' KOLKATA',
' MIHIJAM',
' MUMBAI',
' MYSURU (MYSORE)',
' NAGPUR (MS)',
' NEW DELHI',
' PARGI',
' PONDICHERRY',
' RAIPUR',
' ROURKELA',
' SALEM',
' SOMALWADA - NAGPUR',
' SRI KALAHASTHI - CHITTOR',
' TIRUVALLUR',
' TUMAKURU',
' VISAKHAPATNAM',
' VIZIANAGARAM',
'29160-904 - SERRA / ES / BRAZIL',
'ABU DHABI, UAE',
'Andhra Pradesh ',
'Avenida Brigadeiro Eduardo Gomes,Ba',
'BANGKOK',
'BANGKOK - THAILAND',
'BELGIUM',
'CANADA T3L 0C9',
'Chhattisgarh ',
'Delhi ',
'Dubai ',
'EGYPT',
'EGYPT ',
'GENEVA',
'GENOA - ITALY',
'GERMANY',
'Geneva GE',
'Gujarat ',
'HONG KONG',
'Hong Kong Island HK',
'ISKENDERUN',
'ISRAEL',
'ISTANBUL, TURKEY',
'ITALY',
'JAPAN',
'JORDON',
'KINGDOM OF BAHRAIN',
'KOREA',
'KUWAIT',
'Karnataka ',
'Kerala ',
'LAKE TOWER, DUBAI',
'LIMASSOL, CYPRUS',
'LONDON',
'MACEDONIA',
'MEXICO CP',
'Maharashtra ',
'NEW TERRITORIES, HONG KONG',
'NEW ZEALAND',
'Orissa ',
'Outside India OI',
'Pondicherry ',
'Rajasthan ',
'SHARJAH',
'SHEUNG WAN, HONG KONG',
'SINGAPORE',
'SOHAR, SULTANATE OF OMAN',
'SWEDEN',
'SWITZERLAND',
'Schwyz SZ',
'Singapore SG',
'TAIPEI TAIWAN, ROC',
'THAILAND',
'TOKYO',
'TOKYO - JAPAN',
'TOKYO, JAPAN',
'TURKEY',
'Tamil Nadu ',
'Telangana ',
'Thailand',
'United Kingdom',
'WANHAI HONGKONG',
'West Bengal '

]
html_options = ''.join([f'<option>{optio}</option>\n' for optio in options1])

print(html_options)

NameError: name 'options1' is not defined